# Generated by Django 5.2.8 on 2025-11-18 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('home_time_zone', models.CharField(default='UTC', max_length=64)),
                ('hod_cycle_type', models.CharField(choices=[('60_7', '60 hours / 7 days'), ('70_8', '70 hours / 8 days')], default='70_8', max_length=8)),
                ('short_haul_eligible', models.BooleanField(default=False)),
                ('cdl_required', models.BooleanField(default=True)),
                ('last_34_restart_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_start_time_base', models.DateTimeField(blank=True, null=True)),
                ('vehicle_numbers', models.JSONField(blank=True, default=list)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('carrier_address', models.TextField(blank=True)),
                ('total_miles', models.PositiveIntegerField(default=0)),
                ('shipping_doc_numbers', models.TextField(blank=True, null=True)),
                ('driver_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('co_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_to_carrier_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='ELD.driver')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duty_status', models.CharField(choices=[('off', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On-Duty Not Driving')], max_length=24)),
                ('miles_driven', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_personal_conveyance', models.BooleanField(default=False)),
                ('is_yard_move', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ELD.logsheet')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_miles_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('is_interstate', models.BooleanField(default=True)),
                ('assumed_adverse_conditions', models.BooleanField(default=False)),
                ('short_haul_exception_used', models.CharField(blank=True, max_length=32, null=True)),
                ('time_base', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='ELD.driver')),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_dropoffs', to='ELD.location')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_origins', to='ELD.location')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_pickups', to='ELD.location')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rest', 'Rest'), ('fuel', 'Fuel'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('other', 'Other')], default='other', max_length=16)),
                ('est_arrival', models.DateTimeField(blank=True, null=True)),
                ('est_departure', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ELD.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='ELD.trip')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('distance_miles', models.FloatField(default=0.0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('polyline', models.TextField(blank=True, null=True)),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_ends', to='ELD.location')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_starts', to='ELD.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='ELD.trip')),
            ],
            options={
                'ordering': ['trip', 'index'],
            },
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='ELD.trip'),
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('driving_limit', 'Driving time limit exceeded'), ('window_limit', '14-hour window exceeded'), ('rollover_limit', '60/70 hour limit exceeded'), ('no_34_restart', '34-hour restart missing when expected'), ('no_break', '30 minute break missing'), ('other', 'Other')], max_length=32)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_violations', to='ELD.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hos_violations', to='ELD.trip')),
            ],
        ),
        migrations.CreateModel(
            name='FuelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('gallons', models.FloatField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ELD.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_events', to='ELD.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ELDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_events', to='ELD.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eld_events', to='ELD.trip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=64)),
                ('vin', models.CharField(blank=True, max_length=64, null=True)),
                ('odometer', models.PositiveIntegerField(default=0, help_text='miles')),
                ('max_range_miles', models.PositiveIntegerField(default=1000, help_text='approx range miles between fueling')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='ELD.driver')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='ELD.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='logsheet',
            unique_together={('trip', 'date')},
        ),
    ]
