
import React from "react";
import { PDFDownloadLink, Document, Page, View, Text, StyleSheet, Image } from "@react-pdf/renderer";

// (option) enregistrer une font si besoin:
// Font.register({ family: 'DejaVuSans', src: '/fonts/DejaVuSans.ttf' });

const styles = StyleSheet.create({
  page: { fontSize: 11, padding: 18, fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  title: { fontSize: 16, fontWeight: "bold" },
  sectionRow: { flexDirection: "row", marginBottom: 6 },
  label: { width: "30%", fontWeight: "bold" },
  value: { width: "70%" },
  tableRow: { flexDirection: "row", borderTopWidth: 1, borderColor: "#ddd", paddingTop: 4, paddingBottom: 4 },
  small: { fontSize: 9 },
  // zone timeline / grille
  gridContainer: { marginTop: 8, borderWidth: 1, padding: 6 },
  gridHeader: { flexDirection: "row", justifyContent: "space-between" },
  footer: { marginTop: 12, fontSize: 9 },
});

const TripPdfDocument = ({ trip, driver, vehicle, routeSegments, stops, mapImageBase64 }) => {
  // mapImageBase64 optional — include a snapshot
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Driver Daily Log</Text>
          <Text style={styles.small}>{new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.sectionRow}>
          <Text style={styles.label}>Driver</Text>
          <Text style={styles.value}>{driver?.full_name || "—"}</Text>
        </View>

        <View style={styles.sectionRow}>
          <Text style={styles.label}>Vehicle</Text>
          <Text style={styles.value}>{vehicle?.registration || "—"} / VIN: {vehicle?.vin || "—"}</Text>
        </View>

        <View style={styles.sectionRow}>
          <Text style={styles.label}>Trip start</Text>
          <Text style={styles.value}>{trip?.start_datetime || "—"}</Text>
        </View>

        <View style={styles.gridContainer}>
          <Text style={{ fontSize: 12, marginBottom: 6 }}>Timeline (extrait des LogEntries)</Text>
          {routeSegments && routeSegments.length > 0 ? (
            routeSegments.map((seg, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={{ width: "40%" }}>{seg.start_location?.name || "—"} → {seg.end_location?.name || "—"}</Text>
                <Text style={{ width: "20%" }}>{seg.distance_miles?.toFixed(1)} mi</Text>
                <Text style={{ width: "40%" }}>{seg.duration_minutes} min</Text>
              </View>
            ))
          ) : (
            <Text>Aucun segment</Text>
          )}
        </View>

        {mapImageBase64 && (
          <View style={{ marginTop: 10 }}>
            <Text style={{ marginBottom: 6, fontSize: 12 }}>Carte</Text>
            <Image src={mapImageBase64} style={{ width: 520, height: 200 }} />
          </View>
        )}

        <View style={styles.footer}>
          <Text>Generated by EldLogbookTrip</Text>
        </View>
      </Page>
    </Document>
  );
};

export default function TripPdfGenerator({ trip, driver, vehicle, routeSegments, stops, mapImageBase64 }) {
  return (
    <div>
      <PDFDownloadLink
        document={<TripPdfDocument trip={trip} driver={driver} vehicle={vehicle} routeSegments={routeSegments} stops={stops} mapImageBase64={mapImageBase64} />}
        fileName={`trip_${trip?.id || "unknown"}_log.pdf`}
      >
        {({ loading }) => (loading ? "Préparation PDF..." : <button className="btn">Télécharger le PDF</button>)}
      </PDFDownloadLink>
    </div>
  );
}
